name: "Audit"
description: "Audit information"
runs:
  using: "composite"
  steps:
    - name: Audit project cd ${{ matrix.project }}
      run: cd ${{ matrix.project }} && pnpm install && pnpm run audit --prod
      shell: bash
