name: "Audit"
description: "Audit information"
inputs:
  project:
    description: "The project directory"
    required: true
runs:
  using: "composite"
  steps:
    - name: Audit project cd ${{ inputs.project }}
      run: cd ${{ inputs.project }} && pnpm install && pnpm run audit --prod
      shell: bash
