name: "Lint"
description: "Runs a lint check on the innoverse next app"
runs:
  using: "composite"
  steps:
    - name: Install node in ${{ matrix.project }}
      run: cd ${{ matrix.project }} && pnpm install && pnpm run lint
      shell: bash
