// file generated by the Paraglide-Next init command
import { Middleware, Navigation, PrefixStrategy } from '@inlang/paraglide-next';

import type { AvailableLanguageTag } from '@/src/paraglide/runtime';

const strategy = PrefixStrategy<AvailableLanguageTag>({ prefixDefault: 'never' });

export const middleware = Middleware({ strategy });
export const { Link, useRouter, usePathname, redirect, permanentRedirect } = Navigation({ strategy });
